/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JButton;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author user
 */
public class SimpleGame extends javax.swing.JFrame {

    private int iTurn = 1;
    private JButton[] buttons = new JButton[9];
    private String[] board = new String[9];
    /**
     * Creates new form SimpleGame
     */
    public SimpleGame() {
        initComponents();
        
        buttons[0] = btnCell0;
        buttons[1] = btnCell1;
        buttons[2] = btnCell2;
        buttons[3] = btnCell3;
        buttons[4] = btnCell4;
        buttons[5] = btnCell5;
        buttons[6] = btnCell6;
        buttons[7] = btnCell7;
        buttons[8] = btnCell8;
        
        for(var i=0; i<9; i++)
        {
            buttons[i].setText("   ");
            buttons[i].addMouseListener(new MouseAdapter() {
                @Override public void mouseClicked(MouseEvent evt) {
                    anyButtonClicked(evt);
                }
            });
        }
    }
    
    private void anyButtonClicked(MouseEvent evt)
    {
        //System.out.println(evt.getSource());
        
        JButton button = (JButton) evt.getSource();
        
        if(iTurn%2 == 0) button.setText("O");
        else button.setText("X");
        iTurn++;
        
        for(var i=0; i<9; i++)
        {
            if(buttons[i] == button)
            {
                board[i] = buttons[i].getText();
            }
        }
        
        for(var i=0; i<9; i++)
        {
            System.out.print(board[i]+", ");
        }
        System.out.println("\n");
        
        button.setSize(87, 87);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCell0 = new javax.swing.JButton();
        btnCell1 = new javax.swing.JButton();
        btnCell2 = new javax.swing.JButton();
        btnCell5 = new javax.swing.JButton();
        btnCell4 = new javax.swing.JButton();
        btnCell3 = new javax.swing.JButton();
        btnCell8 = new javax.swing.JButton();
        btnCell7 = new javax.swing.JButton();
        btnCell6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCell0.setBackground(new java.awt.Color(204, 255, 0));
        btnCell0.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        btnCell0.setText("X");
        btnCell0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCell0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCell0MouseClicked(evt);
            }
        });

        btnCell1.setBackground(new java.awt.Color(204, 255, 0));
        btnCell1.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        btnCell1.setText("X");
        btnCell1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCell2.setBackground(new java.awt.Color(204, 255, 0));
        btnCell2.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        btnCell2.setText("X");
        btnCell2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCell5.setBackground(new java.awt.Color(204, 255, 0));
        btnCell5.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        btnCell5.setText("X");
        btnCell5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCell4.setBackground(new java.awt.Color(204, 255, 0));
        btnCell4.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        btnCell4.setText("X");
        btnCell4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCell3.setBackground(new java.awt.Color(204, 255, 0));
        btnCell3.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        btnCell3.setText("X");
        btnCell3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCell8.setBackground(new java.awt.Color(204, 255, 0));
        btnCell8.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        btnCell8.setText("X");
        btnCell8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCell7.setBackground(new java.awt.Color(204, 255, 0));
        btnCell7.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        btnCell7.setText("X");
        btnCell7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCell6.setBackground(new java.awt.Color(204, 255, 0));
        btnCell6.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        btnCell6.setText("X");
        btnCell6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCell6)
                        .addGap(18, 18, 18)
                        .addComponent(btnCell7)
                        .addGap(18, 18, 18)
                        .addComponent(btnCell8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCell3)
                        .addGap(18, 18, 18)
                        .addComponent(btnCell4)
                        .addGap(18, 18, 18)
                        .addComponent(btnCell5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCell0)
                        .addGap(18, 18, 18)
                        .addComponent(btnCell1)
                        .addGap(18, 18, 18)
                        .addComponent(btnCell2)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCell0, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCell1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCell2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCell3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCell4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCell5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCell6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCell7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCell8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCell0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCell0MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCell0MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCell0;
    private javax.swing.JButton btnCell1;
    private javax.swing.JButton btnCell2;
    private javax.swing.JButton btnCell3;
    private javax.swing.JButton btnCell4;
    private javax.swing.JButton btnCell5;
    private javax.swing.JButton btnCell6;
    private javax.swing.JButton btnCell7;
    private javax.swing.JButton btnCell8;
    // End of variables declaration//GEN-END:variables
}
